name       : checklt          # name of the package
version    : 0.0.3       # version of the package
kind       : tool                     # one of tool or spec(s)
description: CheckLT is a program verification tool for Java which can help you use taint tracking to find defects in your software.

author:
  - name: John L. Singleton
    email: jsinglet@gmail.com


assets:
    - asset   : MAIN
      name    : CheckLT Distribution
      url     : https://github.com/checklt/checklt/releases/download/checklt-OCT022015/checklt-OCT022015.tar.gz
      platform: all

assumes:
  - cmd: java -version
    matches: java version "1.[7].*
    message: "Please install a recent version of Java 1.7."
    platform: all

install:
  - cmd: tar -zxvf MAIN
    description: Unpacking CheckLT Distribution...
    platform: all