name       : checklt          # name of the package
version    : 0.0.1       # version of the package
kind       : tool                     # one of tool or spec(s)
description: CheckLT is a program verification tool for Java which can help you use taint tracking to find defects in your software.

author:
  - name: John L. Singleton
    email: jsinglet@gmail.com

#
# assets that make up THIS package
#

# assets:
#     - asset   : MAIN
#       name    : my-asset
#       url     : http://www.openjml.org/downloads/1.1.2.tar.gz  
#       platform: all


assumes:
  - cmd: java -version
    matches: java version "1.[7-9].*
    message: "Please install a recent version of Java 1.7 or greater."
    platform: all

install:
  - cmd: unzip MAIN
    description: Unpacking FindBugs Distribution...
    platform: all